### ISSUE TITLE
Having trouble init_search miniF2F proofs

### ISSUE THREAD

**Issue by Some-random** [openai/lean-gym#32]
I followed the instructions given in the README document, using the theorem [int.prime.dvd_mul](https://github.com/openai/lean-gym#usage) as a test case, and everything worked as expected. However, when I tried to replace 'int.prime.dvd_mul' with [mathd_algebra_141](https://github.com/openai/miniF2F/blob/main/lean/src/test.lean#L70) - a theorem from the miniF2F collection, the system returned the following error message:

"{"error":"not_a_theorem: name=mathd_algebra_141 open_ns=","proof_steps":[],"search_id":null,"tactic_state":null,"tactic_state_id":null}"

As my experience with Lean is rather limited, I'm finding it challenging to pinpoint and resolve the issue. I'd greatly appreciate any assistance or direction you could provide to help me navigate this hurdle.

![image](https://github.com/openai/lean-gym/assets/10830859/88ea7796-a4ae-44f9-932a-c37f4934ea21)

**Comment by wiio12** [comment]
Hi @Some-random, sorry for the late reply. Have you tried to run the `scripts/setup_miniF2F.sh` script? This will complete the setup for miniF2F.

**Comment by Some-random** [comment]
Hi @wiio12 , thanks for the help. I've managed to load miniF2F theorems!
